### ISSUE TITLE
Error: Error loading workspace IDL for test

### ISSUE THREAD

**Issue by Hretic** [arunavo4/sol-sell-escrow#2]
hi when i run `anchor test` , after successful build & deploy i get this error  `Error: Error loading workspace IDL for test` 

```
yarn run v1.22.18
warning package.json: No license field
$ /home/max/solana-project/sol-sell-escrow-v3/node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'

Error: Error loading workspace IDL for test
    at /home/max/solana-project/sol-sell-escrow-v3/node_modules/@project-serum/anchor/src/workspace.ts:102:13
    at Array.forEach (<anonymous>)
    at attachWorkspaceOverride (/home/max/solana-project/sol-sell-escrow-v3/node_modules/@project-serum/anchor/src/workspace.ts:91:31)
    at Object.get (/home/max/solana-project/sol-sell-escrow-v3/node_modules/@project-serum/anchor/src/workspace.ts:72:9)
    at Suite.<anonymous> (/home/max/solana-project/sol-sell-escrow-v3/tests/escrow.ts:15:38)
    at Object.create (/home/max/solana-project/sol-sell-escrow-v3/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/home/max/solana-project/sol-sell-escrow-v3/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/home/max/solana-project/sol-sell-escrow-v3/tests/escrow.ts:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/home/max/solana-project/sol-sell-escrow-v3/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/home/max/solana-project/sol-sell-escrow-v3/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.exports.requireOrImport (/home/max/solana-project/sol-sell-escrow-v3/node_modules/mocha/lib/nodejs/esm-utils.js:60:20)
    at Object.exports.loadFilesAsync (/home/max/solana-project/sol-sell-escrow-v3/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at singleRun (/home/max/solana-project/sol-sell-escrow-v3/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (/home/max/solana-project/sol-sell-escrow-v3/node_modules/mocha/lib/cli/run.js:374:5)
error Command failed with exit code 1.
```

**Comment by arunavo4** [comment]
Hi @Hretic, yea somehow this is an issue cant figure out why tho. I will upgrade the whole program to the latest Anchor version. and fix this. watch out for the update in this issue.

**Comment by arunavo4** [comment]
Finally got some time to fix the Contract, Here is the link for just the (contract)[https://github.com/arunavo4/sol-nft-sell-program/tree/main]
